/* ==========================================================================
 * Language Test Phrases
 *
 * @project: React Speech App
 * @author: Andre Goncalves (andre@andregoncalves)
 * @copyright: 2018 Andre Gocalves
 * ==========================================================================
 */

interface LanguageData {
  [key: string]: string[];
}

const data: LanguageData = {
  'en-US': [
    'Hello! How are you?',
    'I don\'t like to study here. It\'s very noisy',
    'Where are you going?',
    'I went to watch a movie.',
    'Are you free tomorrow?',
    'That looks wonderful. How much is it?',
    'Let\'s get a drink.',
    'I really appreciate your help',
    'Excuse me, do you know what time it is?',
    'I’m sorry for the mess. I wasn’t expecting anyone today.',
    'I’m not sure if we should paint the room yellow or blue.',
    'Let’s hire a band to play music.',
    'Actually, I am running a bit behind, but they’ll be done by noon!',
  ],
  'es-ES': [
    'Hola! Cómo estás?',
    'No me gusta estudiar aquí. Es muy ruidoso',
    'A dónde vas?',
    'Fui a ver una película.',
    'Estas libre mañana?',
    'Es muy hermoso. Cuánto cuesta?',
    'Vamos a tomar una cerveza',
    'Aprecio tu ayuda',
    'Sabes qué hora es?',
    'Lo siento. No esperaba a nadie hoy.',
    'No estoy seguro de si deberíamos pintar la habitación de amarillo o azul.',
    'Contratemos una banda de música y fotografiemos el evento.',
    'En realidad, estoy un poco atrasado, pero estarán listos para el mediodía',
  ],
  'fr-FR': [
    'Excusez-moi, où sont les champs elysee?',
    'Où se trouve la station de métro la plus proche?',
    'Un billet, s’il vous plaît.',
    'Nous voudrions commander maintenant.',
    'Qu’est-ce que vous conseillez?',
    'L’addition, s’il vous plaît.',
    'À quelle heure est le film?',
    'Alors nous devons partir maintenant.',
    'Combien de temps vas-tu rester ici?',
    'Alors, qui vient à la fête? Personne ne vient.',
    'Es-tu occupé ce soir?',
    'Pas vraiment. Pourquoi?',
    'Comment es-tu arrivé ici?',
    'A quelle heure finiras-tu de travailler ce soir?',
  ],
  'de-DE': [
    'Tschüss, bis zum nächsten mal',
    'Schönes wetter heute, nicht wahr?',
    'Woher kommen Sie?',
    'Freut mich',
    'Ich habe viel Spaß!',
    'Können Sie das bitte wiederholen?',
    'Was bedeutet das?',
    'zweiunddreißig',
    'Ein Tisch für zwei Personen, bitte',
    'Was ist das beliebteste Gericht?',
    'Bringen Sie mir bitte eine Auswahl von leckeren Sachen',
    'Wohin muss ich jetzt gehen?',
    'Wie spät ist es jetzt?',
    'Gibt es hier in der nähe etwas interessantes zu sehen',
    'Ich suche ein nettes Café in der nähe',
  ],
  'pt-PT': [
    'O que está a fazer? A estudar Português?',
    'Eu vou ao mercado. Quer vir comigo?',
    'Preciso da tua ajuda, não entendo o que está escrito',
    'Fui assistir a um filme ontem',
    'Sim, eu estou livre depois das 5 da tarde.',
    'Quer ir comer alguma coisa? Eu estou faminto!',
    'O que é isso? É um doce. Quer provar?',
    'Está calor hoje, vamos beber cerveja',
    'Eu preciso de acordar cedo',
    'Você já esteve no Japão?',
    'Traz um chá gelado para mim, por favor.',
    'Eu não estou me sentindo muito bem.',
    'Desculpe, não estava à espera de visitas hoje',
  ],
  'it-IT': [
    'Buongiorno! come va?',
    'Bella giornata oggi, vero?',
    'Mi sto divertendo molto',
    'Mi scusi, non capisco',
    'Settecento ottantatré',
    'Cosa mi consiglia?',
    'Mi farebbe un assortimento dei piatti migliori?',
    'A che ora parte il prossimo treno per Roma',
    'Mi scusi, posso farle una domanda?',
    'Mi piace questo. Quanto costa?',
    'Cerco un posto qui in zona dove si mangi bene',
    'C\'è qualche posto interessante da visitare qui in zona?',
    'Sto andando al mercato. Vuoi venire con me?',
    'Devo svegliarmi presto domani.',
    'Forse il mese prossimo. Tu?',
    'A che ora finisci di lavorare stasera?',
  ],
  'ru-RU': [
    'Я собираюсь на рынок. Хочешь присоединиться?',
    'Отлично! Пойдем выпьем по стаканчику.',
    'Не хочешь завтра сходить в кино?',
    'Нет, я из Санкт-Петербу́рг. Ты знаешь где это?',
    'Я благодарен Вам за помощь.',
    'Я не говорю по-русски, но мы сможем общаться через переводчика.',
    'За здоровье!',
    'Ты хочешь танцевать?',
    'Блин, а мне нужно что-нибудь съесть.',
    'Мне нужно завтра рано вставать.',
    'Я не уверен, следует ли рисовать комнату желтым или синим цветом.',
    'На самом деле, я немного позади, но они будут сделаны к полудню!',
  ],
  'nl-NL': [
    'Wat ben je aan het doen?',
    'Omdat ik graag studeer in cafés.',
    'Ik ga naar de markt. Ga je mee?',
    'Wat heb je gisteren gedaan?',
    'Wil je naar een film gaan kijken morgen?',
    'Waar kom je vandaan? Amsterdam?',
    'Een of twee keer per maand.',
    'Ik ga een keer per week.',
    'Laten we bier gaan drinken.',
    'Oké, we zullen ergens anders naartoe gaan.',
    'Ik moet vroeg opstaan morgen.',
    'Dus, wie gaat er naar het feest?',
    'Nee, ik ben daar nog nooit geweest.',
    'Het is zo heet. Ik ga dood.',
    'Ik ga naar de winkel. Wil je ook iets?',
    'In een café in de buurt van mijn huis. En jij?',
    'Sorry. Ik zal het uitleggen voor jou.',
  ],
};

export default data;
